######################## default configuration ####################
baseURL = "https://kertemkertem.hu"
languageCode = "hu"
title = "Legszebb kert a vidéken!"
theme = "hargo-hugo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  #[[menu.main]]
  #name = "Products"
  #URL = "products/"
  #weight = 1

  [[menu.main]]
  name = "Referenciák"
  URL = "ref/"
  weight = 2

  #[[menu.main]]
  #name = "FAQ"
  #URL = "faq/"
  #weight = 3

  [[menu.main]]
  name = "Kapcsolat"
  URL = "contact/"
  weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Bemutatkotás"
  URL = "/#"
  weight = 1

  [[menu.main]]
  name = "Referenciák"
  URL = "ref/"
  weight = 2

  [[menu.footer]]
  name = "Üzletszabályzat & Adatvédelem"
  URL = "terms-conditions/"
  weight = 4

  [[menu.footer]]
  name = "Kapcsolat"
  URL = "contact/"
  weight = 5

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Bemutatkozás"
# Meta data
description = "Kertrendezés, kertápolás és kerépítészet egy kézből az Ön igényeihez igazítva."
author = "Kertem Kertem"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDS_GJeQ2DHsCgTKcXulvXww05GVYJ1V-Y"
mapLatitude = "47.6418"
mapLongitude = "18.7368"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalyticsID = "G-6BGVMLPKV0" # Your ID
# Contact Information
mobile = "+362012345678"
email = "kapcsolat@kertemkertem.hu"
location = "2528 Úny"
# copyright
copyright = "| Copyright &copy; 2023 Minden jog fenntartva! |"
# Snipcart Credentials
snipcartApiKey = ""
currencySymbol = "€"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = false
  websiteID = ""
  publicKey = ""

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "#"

  [[params.social]]
  icon = "ti-twitter-alt"
  link = "#"

  [[params.social]]
  icon = "ti-youtube"
  link = "#"

  [[params.social]]
  icon = "ti-instagram"
  link = "#"

  [[params.social]]
  icon = "ti-pinterest"
  link = "#"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io
